apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
spec:
  selector:
    app: pihole
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  - protocol: UDP
    port: 53
    targetPort: 53
    name: dns-udp
  - protocol: TCP
    port: 53
    targetPort: 53
    name: dns-tcp
  type: LoadBalancer
  loadBalancerIP: 10.20.150.250
